### ISSUE TITLE
Missing publication for Bag Distance similarity measure

### ISSUE THREAD

**Issue by fathoni** [anhaidgroup/py_stringmatching#51]
The [documentation](https://anhaidgroup.github.io/py_stringmatching/v0.3.x/BagDistance.html) provides information about how to use the bag distance measure, but the explanation refers to a dead link. Could you please update the documentation with the title and author of the original paper? Thank you in advance!

**Comment by pjmartinkus** [comment]
Thank you for bringing this to our attention. We are working on fixing this issue, but for now, [here](http://www-db.disi.unibo.it/research/papers/SPIRE02.pdf) is a working link to correct paper.

**Comment by pjmartinkus** [comment]
We have fixed the documentation to include a working link to the correct paper.
