### ISSUE TITLE
py_stringmatching's jaro_winkler is slower than pure-Python jellyfish's jaro_winkler

### ISSUE THREAD

**Issue by fjsj** [anhaidgroup/py_stringmatching#55]
Hi, I suppose there's something wrong with cython_jaro_winkler. Looks like it's much slower than a pure-Python implementation, like the one in [jellyfish](https://github.com/jamesturk/jellyfish) project.

On my machine, macOS Mojave 10.14.2 (18C54):
```
In [1]: import timeit                                                                                                                                                            

In [2]: timeit.Timer('jw.get_raw_score(\'DIXON\', \'DICKSONX\')', setup='from py_stringmatching.similarity_measure.jaro_winkler import JaroWinkler; jw = JaroWinkler()').timeit(number=10000)
Out[2]: 0.1117161939619109

In [3]: timeit.Timer('jellyfish.jaro_winkler(\'DIXON\', \'DICKSONX\')', setup='import jellyfish').timeit(number=10000) 
Out[3]: 0.004220786038786173
```

Also tested on a Ubuntu 16.04.4 server. Similar results.

Versions:
Python 3.6.7
jellyfish==0.6.1
py-stringmatching==0.4.0

**Comment by fjsj** [comment]
Nevermind. I was misled by jellyfish source code. The correct execution is:
```
import timeit
timeit.Timer('jellyfish.jaro_winkler(\'DIXON\', \'DICKSONX\')', setup='from jellyfish import _jellyfish as jellyfish').timeit(number=10000) 
``` 

Which gives similar results to py_stringmatching.

**Comment by anhaid** [comment]
Hi. Thank you very much for using our code, and I'm glad that this issue has been resolved (and sorry for the late reply. We have been on winter break :). The Magellan team.
